/* MegaQueue
 *
 * Copyright 2015 Daniel Pouzzner
 *
 * mq_rwlock_global.c  2015dec11  daniel.pouzzner@megaqueue.com
 * 
 * global (non-inline) version of mq_rwlock.c
 */

#ifndef MQ_RWLOCK_INHERITPRIORITY_SUPPORT
#  define MQ_RWLOCK_INHERITPRIORITY_SUPPORT
#endif
#ifndef MQ_RWLOCK_INHERITPEAKPRIORITY_SUPPORT
#  define MQ_RWLOCK_INHERITPEAKPRIORITY_SUPPORT
#endif
#ifndef MQ_RWLOCK_STATISTICS_SUPPORT
#  define MQ_RWLOCK_STATISTICS_SUPPORT
#endif
#ifndef MQ_RWLOCK_DEBUGGING_SUPPORT
#  define MQ_RWLOCK_DEBUGGING_SUPPORT
#endif
#ifndef MQ_RWLOCK_EXTRAERRORCHECKING_SUPPORT
#  define MQ_RWLOCK_EXTRAERRORCHECKING_SUPPORT
#endif
#ifdef MQ_RWLOCK_NOCOSTLYERRORCHECKING_SUPPORT
#  undef MQ_RWLOCK_NOCOSTLYERRORCHECKING_SUPPORT
#endif
#ifdef MQ_RWLOCK_NOLOCKTRACKING_SUPPORT
#  undef MQ_RWLOCK_NOLOCKTRACKING_SUPPORT
#endif
#ifdef MQ_RWLOCK_INTELRTM_SUPPORT
#  undef MQ_RWLOCK_INTELRTM_SUPPORT
#endif
#ifndef MQ_RWLOCK_RECURSION_SUPPORT
#  define MQ_RWLOCK_RECURSION_SUPPORT
#endif
#ifndef MQ_RWLOCK_REPORTINVERSIONS_SUPPORT
#  define MQ_RWLOCK_REPORTINVERSIONS_SUPPORT
#endif
#ifndef MQ_RWLOCK_AVERTINVERSIONS_SUPPORT
#  define MQ_RWLOCK_AVERTINVERSIONS_SUPPORT
#endif

#define MQ_RWLOCK_LOCALDEFAULTFLAGS 0UL
#include "mq.h"
#include "mq_rwlock.c"
